#############################################################################
# Makefile for building: MyDocument
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  MyDocument.pro
# Template: subdirs
# Command: C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe -o Makefile MyDocument.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-Journal \
		sub-MajorWindow \
		sub-ViewCheck


sub-Journal-qmake_all:  FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Journal\ && $(MAKE) -f Makefile qmake_all
sub-Journal: FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Journal-make_first: FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Journal-all: FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Journal-clean: FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Journal-distclean: FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Journal-install_subtargets: FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Journal-uninstall_subtargets: FORCE
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MajorWindow-qmake_all:  FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd MajorWindow\ && $(MAKE) -f Makefile qmake_all
sub-MajorWindow: FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MajorWindow-make_first: FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MajorWindow-all: FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MajorWindow-clean: FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MajorWindow-distclean: FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MajorWindow-install_subtargets: FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MajorWindow-uninstall_subtargets: FORCE
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-ViewCheck-qmake_all:  FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd ViewCheck\ && $(MAKE) -f Makefile qmake_all
sub-ViewCheck: FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-ViewCheck-make_first: FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-ViewCheck-all: FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-ViewCheck-clean: FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-ViewCheck-distclean: FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-ViewCheck-install_subtargets: FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-ViewCheck-uninstall_subtargets: FORCE
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: MyDocument.pro C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qdevice.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/sanitize.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/gcc-base.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-base.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/angle.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-vulkan.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-win32.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-desktop.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qconfig.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bodymovin_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_zlib_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/toolchain.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qml_debug.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qmake_use.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/file_copies.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exceptions.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/lex.prf \
		MyDocument.pro
	$(QMAKE) -o Makefile MyDocument.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qdevice.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/device_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/sanitize.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/gcc-base.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-base.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/angle.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-vulkan.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-win32.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-desktop.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qconfig.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bodymovin_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_zlib_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_functions.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/win32-g++/qmake.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/toolchain.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/default_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/resolve_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qml_debug.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/precompile_header.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/warn_on.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qmake_use.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/file_copies.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/testcase_targets.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exceptions.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/yacc.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/lex.prf:
MyDocument.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile MyDocument.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-Journal-qmake_all sub-MajorWindow-qmake_all sub-ViewCheck-qmake_all FORCE

make_first: sub-Journal-make_first sub-MajorWindow-make_first sub-ViewCheck-make_first  FORCE
all: sub-Journal-all sub-MajorWindow-all sub-ViewCheck-all  FORCE
clean: sub-Journal-clean sub-MajorWindow-clean sub-ViewCheck-clean  FORCE
distclean: sub-Journal-distclean sub-MajorWindow-distclean sub-ViewCheck-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Journal-install_subtargets sub-MajorWindow-install_subtargets sub-ViewCheck-install_subtargets FORCE
uninstall_subtargets: sub-Journal-uninstall_subtargets sub-MajorWindow-uninstall_subtargets sub-ViewCheck-uninstall_subtargets FORCE

sub-Journal-debug:
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MajorWindow-debug:
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-ViewCheck-debug:
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-Journal-debug sub-MajorWindow-debug sub-ViewCheck-debug

sub-Journal-release:
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MajorWindow-release:
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-ViewCheck-release:
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-Journal-release sub-MajorWindow-release sub-ViewCheck-release

sub-Journal-check:
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MajorWindow-check:
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-ViewCheck-check:
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-Journal-check sub-MajorWindow-check sub-ViewCheck-check

sub-Journal-benchmark:
	@if not exist Journal\ mkdir Journal\ & if not exist Journal\ exit 1
	cd Journal\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\Journal\Journal.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MajorWindow-benchmark:
	@if not exist MajorWindow\ mkdir MajorWindow\ & if not exist MajorWindow\ exit 1
	cd MajorWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\MajorWindow\MajorWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-ViewCheck-benchmark:
	@if not exist ViewCheck\ mkdir ViewCheck\ & if not exist ViewCheck\ exit 1
	cd ViewCheck\ && ( if not exist Makefile $(QMAKE) -o Makefile I:\git\DocumentPro\ViewCheck\ViewCheck.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Journal-benchmark sub-MajorWindow-benchmark sub-ViewCheck-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

